### ISSUE TITLE
Android Firefox: Slider shows visible arrows

### ISSUE THREAD

**Issue by FrostKiwi** [georgealways/lil-gui#122]
Not sure if this is a regression or I just never noticed it, but Firefox on Android now shows arrows for inc/dec, which are on the input tags of type range normally.
Not the case with dat.gui, not the case with lil.gui + another browser and I swear also not the case a month ago with lilgui.

Also the case with the kitchen sink sample:

![Screenshot_20231031-161809](https://github.com/georgealways/lil-gui/assets/60887273/e13a1ecd-cf5f-4dfb-8c73-734c2f8c3c10)

**Comment by georgealways** [comment]
Thanks for the catch—yes I must have introduced that regression in the release a few days ago. I removed the CSS required to hide those because it wasn't necessary in the mobile browsers that I tested.

I'll release a patch that hides these again shortly. In the meantime, if you use version 0.18.2 that issue should go away. Thanks!

**Comment by georgealways** [comment]
Just released a patch that fixes this regression. Thanks again!
