### ISSUE TITLE
GitHub actions for publishing to NPM and creating "Releases"

### ISSUE THREAD

**Issue by georgealways** [georgealways/lil-gui#20]
There's two things in this repository I'd love to automate and I think GitHub Actions enable them:

1. Publishing to NPM
2. Creating GitHub "Releases"—how does this work when the built source is in `.gitignore`?

I'm hoping someone familiar with Actions could lend a hand.

**Comment by Degubi** [comment]
Hi, are talking about something like this release? https://github.com/Degubi/lil-gui/releases/tag/test
The Github actions script can be found in the .github/workflows folder
Basically it doesn't matter if a folder is .gitignore-d because you have to specify what you want to upload to a release (at least this is how I usually do it)
The procedure is simple: you create a new release in the releases menu, and after a few seconds the actions job gets triggered and when it finishes it just uploads the specified files to the release like the one I sent you.

**Comment by georgealways** [comment]
Hey—that's exactly what I'm looking for, thanks! I'm getting a better sense of how Actions work now too ... it's sort of just a list of terminal commands, huh? 

This takes care of the Release part. Ideally the same script could take a version parameter and run `npm version VERSION && npm publish` but I'm not sure how that would work when it comes to authenticating with NPM...

Thanks again for putting this together!

**Comment by Degubi** [comment]
You could use the ${{github.ref}} for the version part (this variable is the tag name). You can read more about these variables here: https://docs.github.com/en/actions/learn-github-actions/contexts

For the authentication I don't know how would I do it, but I've done similar in this file using Github's package system:
https://github.com/Degubi/Js-Seq/blob/master/.github/workflows/release.yml
In this file I set the registry url and set the NODE_AUTH_TOKEN from a secrets variable. I don't know if the process is the same/similar to publishing to npm.
