### ISSUE TITLE
slider handles disappear when initialized with value out of range

### ISSUE THREAD

**Issue by greggman** [georgealways/lil-gui#21]
I'm not sure if you care about this but.... dat.gui shows a bar, lil.gui shows a line, the problem with the line is if the starting value is greater than the range, lil.gui shows nothing (because the line is effectively beyond the right edge of the control) but dat.gui shows a full bar which is arguably more useful or at least represents the situation better.

Here's an example

https://jsgist.org/?src=a2ca7508d6bd2b9ae7023517e70eccc0

<img width="762" alt="Screen Shot 2021-11-26 at 00 29 08" src="https://user-images.githubusercontent.com/234804/143550502-53c1d4fe-59db-4fb0-8565-fddcce7de653.png">

Of course the value is out of range, but dropping in lil.gui suddenly things that used to show as full now show as empty.

**Comment by Peque** [comment]
In my opinion the line is great, because it is more neutral. Imagine a range between [-1, 1], or a number representing an orientation in degrees [0, 360]. In those cases it doesn't make much sense to talk about "full" or "empty", nor "0 %" or "100 %".

Maybe the issue is that the GUI is not adjusting initial values to the accepted range? In example: if you input 60 by hand, they will both adjust the value to 50 and display the slider as expected. Perhaps the GUI could adjust initial values to accepted ranges on init.

On the bright side... it helped you debug initial values that were not in the accepted range! :joy:

**Comment by georgealways** [comment]
Hey Gregg! No that's totally valid, at very least the line should be probably clamped to 0-100%.

Just to reveal my thinking behind the line vs fill:

- **Wanted lil-gui to be less colorful to keep focus on the content**
- If you've never seen dat.gui before, the fill at 100% or 0% doesn't scream "slider"

**Comment by georgealways** [comment]
So the display will definitely be clamped in the next release. I'm also thinking about something like this for indicating the value is out of bounds.

<img width="264" alt="Screen Shot 2021-11-26 at 8 58 23 AM" src="https://user-images.githubusercontent.com/238907/143592724-ebcb0f7e-cf96-4951-9b32-c2b6ea7fc1e2.png">

**Comment by Peque** [comment]
Wouldn't it make sense to always clamp the value on init? To me, it makes sense, since any future interaction with the control will always result in a clamped value. So, for example, if you try to initialize a value with 2, when the maximum is 1, lil-gui could set the value to 1.

**Comment by georgealways** [comment]
@Peque No, I don't think the GUI should modify any values until you touch it. Ideally your code should function the same way in the presence or absence of the GUI, which wouldn't be the case if you're relying on it for clamping.
