### ISSUE TITLE
empty folders show 'empty' in lil.gut but nothing in dat.gui

### ISSUE THREAD

**Issue by greggman** [georgealways/lil-gui#38]
I'm guessing this is intentional but just FYI, it kind of breaks things. In dat.gui you could use an empty folder as a label/separator since it wouldn't show anything but itself. With lil.gui, since it shows "empty", those usages kind of break or a least don't look nice

https://jsgist.org/?src=32828379140004c21e3bbc698b360474

<img width="939" alt="Screen Shot 2022-01-29 at 11 47 22" src="https://user-images.githubusercontent.com/234804/151675427-7f00590f-224b-4bff-9a2e-75be35290366.png">

**Comment by georgealways** [comment]
Yea, I wanted to alleviate confusion for this very use case: since lil-gui doesn't indent first level folders, without the "Empty" line, those values would look like they belonged to the folder. I think the real "breaking" change here is that folders are open by default.

You've got me thinking there needs to be like a dat.gui => lil-gui polyfill 😅
