### ISSUE TITLE
onBeforeChange

### ISSUE THREAD

**Issue by jonlepage** [georgealways/lil-gui#40]
hi, can we have a way to inject a cb before change operate plz ?

**Comment by georgealways** [comment]
Hey, do you mind describing the use-case, and how you would want onBeforeChange to work?

**Comment by georgealways** [comment]
Got it, thanks for the details!

In the example it seems like you're primarily using this onBeforeChange method to constrain values (clamping or limiting decimals), right? 

I'll have a think on whether the library should include something like this.

**Comment by djmisterjon** [comment]
> Got it, thanks for the details!
> 
> In the example it seems like you're primarily using this onBeforeChange method to constrain values (clamping or limiting decimals), right?
> 
> I'll have a think on whether the library should include something like this.

yes but is a very dirty code "experiment", i will for sure search a more cleaner way and avoid this approach.

**Comment by georgealways** [comment]
Makes sense.  It feels like the constraining you're doing in `onBeforeChange` can be done with the library's built in functionality. I'm curious why you're not just using `step: .1` instead of `.toFixed(1)`? Or why you're using `_.clamp` when the library already provides `min` and `max`?

It seems like what you're after might be better called "mutate" or "transform". I'm having trouble thinking of other use-cases. It differs from the other `onChange` handlers since they don't return anything.

**Comment by djmisterjon** [comment]
> Makes sense. It feels like the constraining you're doing in `onBeforeChange` can be done with the library's built in functionality. I'm curious why you're not just using `step: .1` instead of `.toFixed(1)`? Or why you're using `_.clamp` when the library already provides `min` and `max`?
> 

yes, it's because for now 'min' 'max' 'step' only accepts a Number in param, but I need to be able to pass Callbacks instead to get more customization.
but I'll get back to you with a better and cleaner answer in a few days when I will rewrite the clean code and resolve my ambiguities.
Otherwise, thank you, your libs seem cleaner to me than dat.gui at the time !

**Comment by georgealways** [comment]
Got it—basically you want "dynamic" constraints. I'll have to think more on that.

Thanks for the kind words.
