### ISSUE TITLE
Question: how to hide/show folders/controllers?

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#6]
Even though `dat.gui` didn't have a proper API to do it, it was possible to hide/show specific folders and controllers. See:

https://github.com/dataarts/dat.gui/issues/259

Is there a way to do something similar with `lil-gui`?

**Comment by georgealways** [comment]
Sure, both GUI and Controller expose their domElement and you can do anything you want with that. 

```js
GUI.prototype.hide = function() { this.domElement.style.display = 'none' }
GUI.prototype.show = function() { this.domElement.style.display = '' }
```

You could do the same to the Controller class to give it those methods. Folders would get them automatically since they're just instances of GUI. 

That should get you by for now, but I could see something like this coming back to the library core.

**Comment by Peque** [comment]
@georgealways Thanks for the tip, I'll try it out! :blush:

**Comment by Peque** [comment]
Works great, thanks again! :tada: 

Feel free to close, or leave open if you think these methods may get implemented in a future release. :blush:

**Comment by Niminem** [comment]
Yes, please let's get the show/hide methods in lilgui

**Comment by georgealways** [comment]
`gui.hide()` and `show()` are back in 0.16.0
