### ISSUE TITLE
onFinishChange

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#7]
It seems the `onChange` function has been implemented, but the `.onFinishChange` is just an alias, according to the documentation.

Are there any plans to implement this or is there a way to workaround it? :blush: 

Use case
---

I have an editor in which the user can edit parameters using click-and-drag on the slider or the value in the controllers to see the changes applied in real-time. These changes, however, end up being a lot when the user interacts with the controller even just one second.

Having `onFinishChange` allows the interface to call a "save state" function after the change has finished to make a snapshot of the state and allow undo operations with CTRL+Z afterwards.

Without this function, if I were to call the "save state" function on each `.onChange`, I would end up with thousands of states to undo if the user wanted to go back to the previous state.

**Comment by georgealways** [comment]
Yea, `onFinishChange` was pretty rare in the dat.gui projects I was looking at and it simplified things a bit to leave it out. Your use case is totally valid though. For now you could use a [debounce](https://underscorejs.org/docs/modules/debounce.html) function in the `onChange` handler:

```js
gui.add( ... ).onChange( debounce( myfunc, 20 ) )
```

...but that's not ideal, because you'd still trigger `myfunc` if the user kept a slider knob still for 20ms. I could see `onFinishChange` coming back for that reason. I may also un-alias the two before then: I imagine people were likely to use this handler for expensive stuff.

**Comment by Peque** [comment]
Yeah, I guess a I could debounce state saving for 1-2 seconds as a workaround.

I would want to keep the real-time `.onChange` effect, so I guess the debounce could be called from the `.onChange` callback. I need to check whether other functions are using the same callback and if that could affect them.

Thanks for considering adding the function back! :blush:

**Comment by georgealways** [comment]
onFinishChange is back as of 0.13. please enjoy~
