### ISSUE TITLE
Move --title-height custom property to .lil-gui?

### ISSUE THREAD

**Issue by teddybradford** [georgealways/lil-gui#75]
Is there a reason that `--title-height: calc(var(--widget-height) + var(--spacing) * 1.25);` is a declaration in `.lil-gui .title` instead of with the rest of the custom props in `.lil-gui`?

If not I think it would be nice to keep all the custom props in the root `.lil-gui` class.

**Comment by georgealways** [comment]
Hmm, I probably just didn't think to "expose" it since it was a product of other vars. But you're right, there's no reason it couldn't sit next to the other theme vars in the root class if you want to keep that all together. 

Let's move it up. Luckily if someone has already targeted `.lil-gui .title` with that prop, their CSS should still work after this change.

**Comment by georgealways** [comment]
That's in as of 0.18, thanks for calling this out!
