### ISSUE TITLE
How to update options without recreating control with .options()?

### ISSUE THREAD

**Issue by fagci** [georgealways/lil-gui#86]
How to do this?
dat.gui works as expected: [codepen.io](https://codepen.io/fagcinsk/pen/JjBOJZN?editors=1010)

**Comment by georgealways** [comment]
Right now there's no way to update the options on an existing option controller. The `options` method (in both libraries) actually replaces the old controller. dat.gui just has extra logic to make sure that replacement is inserted in the right place. Omitting the methods that dealt with re-ordering controllers saved many lines of code.

**In both libraries, the `options` method shouldn't be called more than once on the same controller, because it returns the controller that replaces the old one. If you were re-assigning `dc = dc.options( ... )` instead, then the dat.gui example would work as you expect. The lil-gui version would move the controller to the end.**

I tried to emphasize that in the [docs](https://lil-gui.georgealways.com/#Controller#options), but maybe it's worth putting something in there about multiple calls to options. 

(Also, heads up: the version you have written for dat.gui actually doesn't work as you specify. You'll notice the second call to options is ignored and the options are still a and b.)

**Comment by antlii** [comment]
Hi George! 
Maybe is there a way to turn off options, for example, now can not be used?
Something like this:
<img width="555" alt="Screenshot at Jan 19 17-55-07" src="https://user-images.githubusercontent.com/52974033/213490403-f25d2f57-f6b7-419b-af42-bfc911c8c7c5.png">

Thanks!

**Comment by georgealways** [comment]
Hi @antlii, there is not—but you do have access to `optioncontroller.$select`, and you can add the disabled attribute to its children as you please.

**Comment by antlii** [comment]
@georgealways Great, that works for me, thanks for the workaround!

**Comment by bigxixi** [comment]
My workaround to update the dropdown list is to add `<option>new item</option>` to the `optionRef.$select.innerHTML`, and `optionRef._$value.push("new item")`, check the demo below 
https://codepen.io/bigxixi/pen/mdGPXXz

but i see if multiple options has a same name, e.g `["A","B","C","C",]` only the first "C"  can be selected, is that a bug?

**Comment by georgealways** [comment]
@bigxixi not sure, but at that point I think you've voided your controller's warranty ;)

OptionController was designed under the assumption that the options would not change. Adding that functionality would probably add more complexity than I could stomach. But I'll leave this open in case anyone else wants to express the need.

**Comment by vinceynhz** [comment]
My use case is async loading of the options. I have an app in which the user will have a list of options to choose from but those options are going to be retrieved from. The current way I think of solving this is to don't add the controller to the gui until the options are loaded, but it might be helpful if I can build my GUI first, then update all controllers by async calls later.

**Comment by georgealways** [comment]
As of 0.19.0, calling `.options()` on an option controller will simply update the options instead of moving / recreating it. But keep in mind the old behavior still applies if calling this method on a non-option controller.
